// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_passwordhash_salt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_passwordhash_salt));
        
        string IMigrationMetadata.Id
        {
            get { return "202109032029446_add_passwordhash_salt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
